"""initial mnigration

Revision ID: 486e7e0b084b
Revises: 
Create Date: 2020-04-23 22:29:23.501981

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '486e7e0b084b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name'),
    schema='capture_adm'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='capture_adm'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['capture_adm.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    schema='capture_adm'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='capture_adm')
    op.drop_table('roles', schema='capture_adm')
    op.drop_table('products', schema='capture_adm')
    # ### end Alembic commands ###
