"""remove test column from users table

Revision ID: 51260a5af4b1
Revises: f4d790819c05
Create Date: 2020-05-02 22:06:50.986740

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '51260a5af4b1'
down_revision = 'f4d790819c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products', schema='capture_adm')
    op.drop_column('users', 'test', schema='capture_adm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='capture_adm')
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('capture_adm.products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('product_name', name='products_product_name_key'),
    schema='capture_adm'
    )
    # ### end Alembic commands ###
