"""column added to User table

Revision ID: cbc2b5d9134d
Revises: 486e7e0b084b
Create Date: 2020-04-23 22:31:52.230671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc2b5d9134d'
down_revision = '486e7e0b084b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.Boolean(), nullable=True), schema='capture_adm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test', schema='capture_adm')
    # ### end Alembic commands ###
