"""collumn added to Products table

Revision ID: f4d790819c05
Revises: cbc2b5d9134d
Create Date: 2020-04-23 22:34:25.377418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d790819c05'
down_revision = 'cbc2b5d9134d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_price', sa.Integer(), nullable=True), schema='capture_adm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_price', schema='capture_adm')
    # ### end Alembic commands ###
